---
- name: Deploy Django App via Docker Compose
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    # Гарантированное удаление старых контейнеров, чтобы не было конфликтов портов
    - name: Force kill Web/Nginx containers
      shell: |
        docker rm -f django_web nginx_proxy || true
      args:
        chdir: "{{ playbook_dir }}"

    - name: Ensure Nginx config has correct permissions
      file:
        path: "{{ playbook_dir }}/nginx/default.conf"
        mode: '0644'

    - name: Start Application
      shell: docker-compose up -d --build --force-recreate web nginx db
      args:
        chdir: "{{ playbook_dir }}"

    - name: Wait for database connection
      pause:
        seconds: 10

    - name: Apply Database Migrations
      shell: docker exec django_web python manage.py migrate --noinput

    - name: Collect Static Files
      shell: docker exec django_web python manage.py collectstatic --noinput