---
- name: Deploy Django App via Docker Compose
  hosts: webservers
  gather_facts: no

  vars:
    project_dir: "/home/ubuntu/app"

  tasks:
    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Copy project files
      synchronize:
        src: ./
        dest: "{{ project_dir }}"
        # rsync_opts нужны, чтобы исключить лишнее и ускорить копирование
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=venv"
          - "--exclude=terraform"
          - "--exclude=__pycache__"
          - "--exclude=jenkins_home"

    # Удаление старых контейнеров (для освобождения порта 80)
    - name: Force kill Web/Nginx containers
      shell: |
        docker rm -f django_web nginx_proxy || true
      args:
        chdir: "{{ project_dir }}"

    - name: Ensure Nginx config has correct permissions
      file:
        path: "{{ project_dir }}/nginx/default.conf"
        mode: '0644'

    - name: Start Application
      shell: docker compose up -d --build --force-recreate web nginx db
      args:
        chdir: "{{ project_dir }}"

    - name: Wait for database connection
      pause:
        seconds: 10

    - name: Apply Database Migrations
      shell: docker exec django_web python manage.py migrate --noinput

    - name: Collect Static Files
      shell: docker exec django_web python manage.py collectstatic --noinput