---
- name: Deploy Django App via Docker Compose
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    # Шаг 1: Убиваем всех, кто занимает 80 порт (на всякий случай)
    - name: Force kill any container occupying port 80
      shell: |
        ID=$(docker ps -q -f "publish=80")
        if [ -n "$ID" ]; then
          docker rm -f $ID
        fi
      ignore_errors: yes

    # Шаг 2: Останавливаем и чистим старые контейнеры через Compose
    - name: Stop and remove application containers
      shell: docker-compose down --remove-orphans
      args:
        chdir: "{{ playbook_dir }}"

    # Шаг 3: Гарантируем права на конфиг
    - name: Ensure Nginx config has correct permissions
      file:
        path: "{{ playbook_dir }}/nginx/default.conf"
        mode: '0644'

    # Шаг 4: Запускаем веб-часть (Дженкинс не трогаем, он и так работает)
    - name: Start Application
      shell: docker-compose up -d --build --force-recreate web nginx db
      args:
        chdir: "{{ playbook_dir }}"

    # Шаг 5: Ждем базу
    - name: Wait for database to be ready
      pause:
        seconds: 15

    # Шаг 6: Миграции и статика (используем имя сервиса 'web', а не имя контейнера)
    - name: Apply Database Migrations
      shell: docker-compose exec -T web python manage.py migrate --noinput
      args:
        chdir: "{{ playbook_dir }}"

    - name: Collect Static Files
      shell: docker-compose exec -T web python manage.py collectstatic --noinput
      args:
        chdir: "{{ playbook_dir }}"