---
- name: Deploy Django App via Docker Compose
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    # 1. Принудительно освобождаем место (удаляем старые контейнеры по именам)
    # Мы не трогаем Jenkins и базу (если она нужна постоянной), но убиваем веб-часть.
    - name: Force remove Web/Nginx containers to avoid conflicts
      shell: |
        docker rm -f django_web nginx_proxy || true
      args:
        chdir: "{{ playbook_dir }}"

    # 2. На всякий случай чистим сирот (благодаря .env это сработает идеально)
    - name: Clean up orphans
      shell: docker-compose down --remove-orphans
      args:
        chdir: "{{ playbook_dir }}"

    # 3. Права на конфиг
    - name: Ensure Nginx config has correct permissions
      file:
        path: "{{ playbook_dir }}/nginx/default.conf"
        mode: '0644'

    # 4. ЗАПУСК. Благодаря .env проект будет называться так же, как у тебя локально.
    - name: Start Application
      shell: docker-compose up -d --build --force-recreate web nginx db
      args:
        chdir: "{{ playbook_dir }}"

    # 5. Ждем базу
    - name: Wait for database connection
      pause:
        seconds: 10

    # 6. Миграции
    - name: Apply Database Migrations
      shell: docker exec django_web python manage.py migrate --noinput

    - name: Collect Static Files
      shell: docker exec django_web python manage.py collectstatic --noinput